version: "3"

services:
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    image: node-auth-service
    restart: unless-stopped
    ports:
      - "8080:8100"
    volumes:
      - ./auth:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    command: npx nodemon index.ts

  votacao-service:
    build:
      context: ./votacao
      dockerfile: Dockerfile
    image: node-votacao-service
    restart: unless-stopped
    ports:
      - "8081:8100"
    volumes:
      - ./votacao:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    links:
      - "auth-service"
      - "filmes-service"
    command: npx nodemon index.ts

  filmes-service:
    build:
      context: ./filmes
      dockerfile: Dockerfile
    image: node-filmes-service
    restart: unless-stopped
    ports:
      - "8082:8100"
    volumes:
      - ./filmes:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    command: npx nodemon index.ts

networks:
  app-network:
    driver: bridge
